### ISSUE TITLE
Issue with specifying go-ipfs 0.10.0

### ISSUE THREAD

**Issue by machawk1** [ibnesayeed/setup-ipfs#80]
I am trying to test ipwb with go-ipfs version 0.10.0 using the `setup-ipfs` action.

https://github.com/oduwsdl/ipwb/pull/745/checks?check_run_id=3806811095

The script resolves the version `0.10.0` to `0.1`.

**Comment by ibnesayeed** [comment]
It is likely not a bug of this repo. I have suggested changes to https://github.com/oduwsdl/ipwb/pull/745 to mitigate this issue.
